### ISSUE TITLE
No updated events if the topology changed

### ISSUE THREAD

**Issue by hessijames79** [svrooij/sonos2mqtt#112] opened 2020-07-26 00:23 UTC
I'm using 3 Sonos 1 and 1 Sonos Connect. Because the Connect tends to heat up my tv cabinet even when it is not in use I cut the power regularly. In case this happens, i. e. the topology changes, sonos2mqtt doesn't send events any more. This can be worked around by restarting the container.

**Comment by svrooij** [comment] 2020-07-27 17:26
I’m guessing you’re using the Sonos Connect as the input IP? It uses events to monitor the topology changes. Those events wont be send if you cut the power. But the other players will know when a player left and will emit the event.

The IP you specify when starting the container will be the player that is subscribed to for group events.

I’m not sure what happens if a player becomes unavailable (power cut) and them comes back again. Probably won’t re-subscribe to all events for somewhere between 1 and 50 minutes depending on when it last refreshed the eventsubscribtion.

**Comment by hessijames79** [comment] 2020-07-27 17:41
Hi svrooij!

> I’m guessing you’re using the Sonos Connect as the input IP? It uses events to monitor the topology changes. Those events wont be send if you cut the power. But the other players will know when a player left and will emit the event.
Actually, I'm using the IP address of a Sonos 1 that is connected all the time.

> The IP you specify when starting the container will be the player that is subscribed to for group events.
In that case, the Connect leaving and reappearing should pose any problems.

Is there any way to detect if the connection is broken or maybe a command I can send via mqtt to restart the connection?

Patrick

**Comment by svrooij** [comment] 2020-07-27 17:58
| Is there any way to detect if the connection is broken or maybe a command I can send via mqtt to restart the connection?

Not yet, but great idea.

**Comment by svrooij** [comment] 2020-08-01 19:05
When [this](https://github.com/svrooij/node-sonos-ts/tree/feature/stable-events) is released, it will be pretty easy to make a command that will refresh all the event subscriptions.

**Comment by svrooij** [comment] 2020-08-12 14:13
@hessijames79 can you verify that the issue is fixed in [3.1.0-beta.1](https://www.npmjs.com/package/sonos2mqtt/v/3.1.0-beta.1)?

It will now refresh the subscriptions more often, retry on failure, try again after 10 minutes and last but not least: You can refresh all the event subscriptions by sending a mqtt message to `sonos/cmd/check-subscriptions`

**Comment by hessijames79** [comment] 2020-08-13 15:55
> @hessijames79 can you verify that the issue is fixed in [3.1.0-beta.1](https://www.npmjs.com/package/sonos2mqtt/v/3.1.0-beta.1)?
> 
> It will now refresh the subscriptions more often, retry on failure, try again after 10 minutes and last but not least: You can refresh all the event subscriptions by sending a mqtt message to `sonos/cmd/check-subscriptions`

Hey @svrooij 
that sounds great. I didn't have much time to test it yesterday but what I already verified is that the subscription is successfully refreshed, not instantly but after some time. Will take a deeper look, especially in the check-subscriptions message and report back.

Patrick

**Comment by hessijames79** [comment] 2020-08-17 19:21
Update: Unfortunately, I cannot reliably reproduce the problem by switching the Connect on and off. On the first try, sonos2mqtt stopped sending events but that did not change instantly upon sending check-subscriptions but later. Then I failed to reproduce a broken subscription. Is there any possibility to output any log information concerning the subscriptions? I set the log level to debug but don't see a single log entry about it, just

> 2020-08-17T19:08:01.463Z [Debug] Mqtt got generic command check-subscriptions
> 2020-08-17T19:08:01.463Z [Debug] Got generic command check-subscriptions from mqtt

and once:

> (node:1) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.0.106:1400/MediaRenderer/AVTransport/Event failed, reason: connect ETIMEDOUT 192.168.0.106:1400
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Note: 192.168.0.106 is neither the player set in SONOS2MQTT_DEVICE nor the Connect turned on and off.

Patrick

**Comment by svrooij** [comment] 2020-08-17 19:55
You can set the `DEBUG` environment variable to `sonos:*` to get plenty of logging.

**Comment by heinz-otto** [comment] 2020-08-18 12:43
I will only give a little feedback to the new beta: It seem to be working. 
I have tested this scenario: One Player is switched off for a few hours, after switching on:

- without this beta, the player was controlable but without any events (feedback) from player
- with this beta I could reestablish the Events: 
- switching on, wait a few sesonds and send check-subscriptions 
- if I am only switching on and waiting for few minutes the Events are reestablished automatically.

Thanks for the feature  :-)
Otto

**Comment by svrooij** [comment] 2020-08-18 14:13
@heinz-otto thanks for your feedback.

It refreshes the events every 10 minutes, counting from the start of the application. So depending on when you started the application it can take any where between 10 seconds and 10 minutes before the events start working again. Or if you send a message to `sonos/cmd/check-subscriptions` it will do an extra refresh.

**Comment by hessijames79** [comment] 2020-08-18 17:37
@svrooij Got nice debug messages. Thank you.

I did some more tests and again failed to reliably reproduce the issue. But given @heinz-otto's results, I guess the issue can be closed. Thanks for the nice update.

Patrick

**Closed** 2020-08-19 18:34 UTC
