### ISSUE TITLE
Spotify trackURI

### ISSUE THREAD

**Issue by flic** [svrooij/sonos2mqtt#59] opened 2020-01-22 17:48 UTC
I'm trying to figure out how to encode a trackURI for Spotify, and I just don't get it.

So, from the dokumentation, the format should look like this:

x-sonos-spotify:spotify:track:30cW9fD87IgbYFl8o0lUze?sid=9&flags=8224&sn=7

The first part is easy enough, and I can get the Spotify URI from the Spotify client which brings me to:

x-sonos-spotify:spotify:track:3b9xTm2eiaCRTGqUEWuzxc

What trips me up is sid, flags and sn. I can't find any information on what that is and how to find them.

**Comment by svrooij** [comment] 2020-01-22 18:02
We got you covered, the [metadata helper](https://github.com/svrooij/node-sonos-ts/blob/master/src/helpers/metadata-helper.ts#L172-L213) has specific support for spotify URLs.

Just use only the spotify uri `spotify:track:3b9xTm2eiaCRTGqUEWuzxc` the Sonos library will guess the rest.

Can you verify? If you found a place in this library where the Spotify uri isn’t supported that probably has to be changed to call the metadata helper before sending to the Sonos lib.

**Comment by flic** [comment] 2020-01-22 18:06
Doesn't seem to work. When I send 

spotify:track:3b9xTm2eiaCRTGqUEWuzxc

...to 'sonos/set/sonos-sovrum/queue' I get "<error> Error executing queue for Sonos Sovrum {}" in the log.

**Comment by flic** [comment] 2020-01-22 18:07
Same result with setavtransporturi

**Comment by svrooij** [comment] 2020-01-24 19:35
I'll fix this later on.

**Comment by svrooij** [comment] 2020-01-24 20:20
I've got an other, "WOMP".....

How are you sending them to the device? Could you show the mqtt message you're sending? I'll try to replicate the issue. I'm always using [mqtt fx](https://mqttfx.jensd.de/) to test this stuff out.

<img width="982" alt="Screenshot 2020-01-24 at 21 13 00" src="https://user-images.githubusercontent.com/1292510/73100814-a3d4eb00-3eee-11ea-86b2-6d1b93e8221e.png">

Or with your track uri. 
<img width="1059" alt="Screenshot 2020-01-24 at 21 16 56" src="https://user-images.githubusercontent.com/1292510/73100972-00d0a100-3eef-11ea-8e64-47944fadb9fc.png">

**Comment by flic** [comment] 2020-01-25 07:41
Ha! I didn't notice until now that we used the same track for testing! :)

<img width="1092" alt="Skärmavbild 2020-01-25 kl  08 36 59" src="https://user-images.githubusercontent.com/400673/73118004-335db680-3f4e-11ea-8d74-74ad422c9750.png">

<img width="614" alt="Skärmavbild 2020-01-25 kl  08 40 19" src="https://user-images.githubusercontent.com/400673/73118018-58eac000-3f4e-11ea-9625-ef61711e995c.png">

**Comment by svrooij** [comment] 2020-01-25 11:28
I think you first have to switch it to an existing queue before you can add anything to the queue. To switch to the queue you send a message to `sonos/set/sonos-vardagsrum/adv-command`

```JSON
{
  "cmd":"SwitchToQueue"
}
```

This might only work if there is a queue, so I suggest to queue one song in the sonos app. Then there is a queue to which you can add Spotify tracks.

**Comment by flic** [comment] 2020-01-25 14:03
I tried the adv-command you suggested, but got back "Error executing adv-command for Sonos Vardagsrum {}"

**Comment by svrooij** [comment] 2020-01-27 21:47
And what happens it you switch to an empty queue from the Sonos app? #

**Comment by flic** [comment] 2020-01-29 08:28
Same result.

**Comment by svrooij** [comment] 2020-01-30 09:57
I cannot reproduce this issue, need more information.

Node version:
sonos2mqtt version:
Sonos software version (see app):
OS:

**Comment by flic** [comment] 2020-02-01 08:38
I'm running the latest published docker image on Ubuntu 19.04 (fully patched)

Sonos software version: 10.6.2, build 54273060

If I cutnpaste a full URI (x-sonos-spotify:spotify:track:2UKMqNCVsHrAYzBZMA0rxL?sid=12&flags=8224&sn=7) and publish that to either 'queue' or to 'setavtransporturi' it works in both cases.

If i do the same thing with the Spotify URI (spotify:track:2UKMqNCVsHrAYzBZMA0rxL) I get

Error executing setavtransporturi for Sonos Vardagsrum {}
Error executing queue for Sonos Vardagsrum {}

**Comment by svrooij** [comment] 2020-03-02 19:28
Can you run the latest version with the following command `DEBUG=sonos:* sonos2mqtt ....` this should enable the debug output.

**Comment by flic** [comment] 2020-03-07 08:58
I published spotify:track:3b9xTm2eiaCRTGqUEWuzxc to sonos/set/sonos-vardagsrum/queue:

```
2020-03-07T08:54:44.147Z sonos:metadata Guessing metadata for spotify:track:3b9xTm2eiaCRTGqUEWuzxc


2020-03-07T08:54:44.149Z sonos:service:avtransport:192.168.240.5 AddURIToQueue({ InstanceID: 0, EnqueuedURI: 'x-sonos-spotify:spotify:track:3b9xTm2eiaCRTGqUEWuzxc?sid=9&flags=8224&sn=7', EnqueuedURIMetaData: { Album: undefined, Artist: undefined, AlbumArtUri: undefined, Title: '', UpnpClass: 'object.item.audioItem.musicTrack', Duration: undefined, ItemId: '00032020spotify%3atrack%3a3b9xTm2eiaCRTGqUEWuzxc', ParentId: undefined, TrackUri: 'x-sonos-spotify:spotify%3atrack%3a3b9xTm2eiaCRTGqUEWuzxc?sid=9&amp;flags=8224&amp;sn=7', ProtocolInfo: undefined, CdUdn: 'SA_RINCON2311_X_#Svc2311-0-Token' }, DesiredFirstTrackNumberEnqueued: 0, EnqueueAsNext: true })


2020-03-07T08:54:44.159Z sonos:service:avtransport:192.168.240.5 Sonos error on AddURIToQueue { faultcode: 's:Client', faultstring: 'UPnPError', detail: { UPnPError: { errorCode: 800 } } }


2020-03-07 09:54:44.160 <error> Error executing queue for Sonos Vardagsrum {"Action":"AddURIToQueue","FaultCode":"s:Client","Fault":"UPnPError","UpnpErrorCode":800,"name":"SonosError"}
```

**Comment by svrooij** [comment] 2020-04-29 17:43
Issue cannot be reproduced and might be fixed by the new version of node-sonos-ts anyway.

**Closed by svrooij** 2020-04-29 17:43 UTC
Labels: need info
